# Generated by Django 4.2.7 on 2023-12-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
